# Generated by Django 4.2.7 on 2023-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyRentalBackend', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
