# Generated by Django 4.2.7 on 2023-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyRentalBackend', '0003_alter_realestate_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='images',
        ),
        migrations.AddField(
            model_name='realestate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
